title: UCB HCI Prelim
description: A Guide for the UC Berkeley HCI Preliminary Exam
theme: just-the-docs

url: https://chanwutk.github.io/ucbhciprelim

aux_links:
  Github: https://github.com/chanwutk/ucbhciprelim
